### ISSUE TITLE
自己编译的 agent 会自动退出

### ISSUE THREAD

**Issue by wxlost** [naiba/nezha#21]
12.14号编译的后端启动一段时间会自动退出
前端和后端同一时间编译的版本.....不知道为啥会这样
log日志:
```
panic: semver: Parse(): Version string empty

goroutine 7 [running]:
github.com/blang/semver.MustParse(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/pkg/mod/github.com/blang/semver@v3.5.1+incompatible/semver.go:319 +0x1c5
main.doSelfUpdate()
        /root/nezha/cmd/agent/main.go:58 +0x7c
created by main.run.func1
        /root/nezha/cmd/agent/main.go:102 +0x45
```

**Comment by naiba** [comment]
收到

**Comment by naiba** [comment]
自行编译需要 -x 设置版本号的，简单的方法是把 `cmd/agent/main.go` 里面的 
```go
version string
rootCmd = &cobra.Command{
```
改成
```go
version = "9.9.9"
rootCmd = &cobra.Command{
```
然后再编译，就不会自动升级退出了
